itk-dev/book_aarhus

src/Command/GraphCreateBookingCommand.php
src/Command/GraphUserBookingsCommand.php
src/Service/MicrosoftGraphService.php
src/Service/MicrosoftGraphServiceInterface.php
tests/Api/BusyIntervalTest.php

https://jira.itkdev.dk/browse/BOOKING-66
Adds command to create booking through Microsoft Graph
Adds command to get bookings containing userid

BOOKING-66: Added command to create booking and get bookings

---

config/api_platform/resource.yaml
config/services.yaml
public/api-spec-v1.json
public/api-spec-v1.yaml

BOOKING-142: Added filters for resources

---

config/services.yaml
public/api-spec-v1.json
public/api-spec-v1.yaml
src/DataFixtures/ResourceFixtures.php
src/Entity/BookingDelete.php
src/Entity/Resources/AAKResource.php
src/Entity/Resources/CvrWhitelist.php
src/Entity/Resources/HolidayOpenHours.php
src/Entity/Resources/LocationType.php
src/Entity/Resources/OpenHours.php
src/MessageHandler/WebformSubmitHandler.php
templates/booking.html.twig
tests/Api/BookingTest.php

* Added resourceEmail filter. 
* Changed entity names to camelCase.

BOOKING-144: Added resourceEmail filter. 

---

src/DataProvider/LocationCollectionDataProvider.php
src/Entity/Main/Location.php
src/Repository/Main/AAKResourceRepository.php

Added requirements that locations should contain text and the hasWhitelist should not be true for resources

BOOKING-178: Added requirements on locations

---

.github/workflows/pr.yml
baseline.xml
composer.json
composer.lock
docker-compose.yml
psalm.xml

https://jira.itkdev.dk/browse/BOOKING-184
Added psalm static analyse tool
N/A
N/A

Added psalm to the mix

---

docker-compose.dev.yml

[BOOKING-181](https://jira.itkdev.dk/browse/BOOKING-181)
Remove basic auth from docker-compose-dev

Disable basic auth

---

docker-compose.server.override.yml

https://jira.itkdev.dk/browse/BOOKING-180
See https://docs.itkdev.dk/docs/server/docker/supervisor
N/A
N/A

BOOKING-180: Added supervisor to consume messages server side

---

README.md
config/packages/monolog.yaml
src/Command/UpdateResourcesCacheCommand.php

https://jira.itkdev.dk/browse/BOOKING-197
Adds progressbar to cache resources command.

BOOKING-197: Added progressbar

---

config/services.yaml
src/Command/UpdateResourcesCacheCommand.php
src/Controller/GetAllResourcesController.php
src/Service/ResourceService.php
src/Service/ResourceServiceInterface.php

https://jira.itkdev.dk/browse/BOOKING-197
Moves shared code into ResourceService.

BOOKING-197: Moved shared code into service

---

src/DataPersister/UserBookingDataPersister.php

https://jira.itkdev.dk/browse/BOOKING-62
Adds security voters to edit/delete booking.

BOOKING-62: Added security voters to edit and delete

---

src/Entity/Resources/AAKResource.php

https://jira.itkdev.dk/browse/BOOKING-145
Added hasWhitelist to serialization

BOOKING-145: Added hasWhitelist to serialization

---

src/DataPersister/UserBookingDataPersister.php
src/Service/BookingServiceInterface.php
src/Service/MicrosoftGraphBookingService.php

https://jira.itkdev.dk/browse/BOOKING-214
* Refactored booking delete code.

BOOKING-214: Refactored booking delete

---

src/Service/NotificationService.php
templates/email-notify-admin.html.twig

https://jira.itkdev.dk/browse/BOOKING-221
Fixes issues with admin notifications when webform submit retrieval fails.

BOOKING-221: Changed issues with admin notification emails

---

src/Service/NotificationService.php

https://jira.itkdev.dk/browse/BOOKING-216
Fix bug in ics file

Changed ics to date

---

src/DataFixtures/ResourceFixtures.php

https://jira.itkdev.dk/browse/BOOKING-212
Add formid to fixtures

Added formid to fixtures

---

src/DataFixtures/ResourceFixtures.php
src/Entity/Resources/AAKResource.php

https://jira.itkdev.dk/browse/BOOKING-218
Add image and description to resource minimum group.
If you have any further comments or questions for the reviewer please add them here.

Added image and description to minimum resource

---

CHANGELOG.md
config/packages/messenger.yaml
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Command/BookingNotificationTestCommand.php
src/DataPersister/UserBookingDataPersister.php
src/Entity/Main/UserBooking.php
src/Enum/NotificationTypeEnum.php
src/Message/SendUserBookingNotificationMessage.php
src/MessageHandler/SendUserBookingNotificationHandler.php
src/Service/MicrosoftGraphBookingService.php
src/Service/NotificationService.php
src/Service/NotificationServiceInterface.php
templates/email-booking-changed.html.twig
templates/email-booking-deleted.html.twig
tests/Api/BookingTest.php

https://jira.itkdev.dk/browse/BOOKING-198
https://jira.itkdev.dk/browse/BOOKING-199
* Fixed issue with GET /user-bookings where pagination was not handled correctly.
* Added check to avoid getting many user-bookings in the past.
* Added notifications to user on edit and delete.
* Added notifications to resource on edit and delete.

BOOKING-199: Added user notifications on booking edit and delete

---

CHANGELOG.md
src/DataFixtures/ResourceFixtures.php

https://jira.itkdev.dk/browse/BOOKING-211
* Updated fixture

BOOKING-221: Changed fixture

---

CHANGELOG.md
composer.lock

https://jira.itkdev.dk/browse/SERV-628
Upgraded symfony/http-kernel symfony/security-bundle with dependencies

Upgraded symfony/http-kernel symfony/security-bundle with dependencies

---

.docker/nginx.conf
.docker/vhost.conf
CHANGELOG.md
docker-compose.dev.yml
docker-compose.redirect.yml
docker-compose.server.override.yml
docker-compose.server.yml
docker-compose.yml

https://jira.itkdev.dk/browse/BOOKING-239
Updated docker setup to itk-version: 3.0.0
N/A
If you have any further comments or questions for the reviewer please add them here.

BOOKING-239: Updated docker setup to itk-version: 3.0.0

---

CHANGELOG.md
migrations_resources/Version20230704034622.php
public/api-spec-v1.json
public/api-spec-v1.yaml
src/DataFixtures/ResourceFixtures.php
src/Entity/Resources/AAKResource.php
src/MessageHandler/CreateBookingHandler.php
src/Service/BookingServiceInterface.php
src/Service/MicrosoftGraphBookingService.php
tests/Api/BookingTest.php

https://jira.itkdev.dk/browse/BOOKING-247
Added acceptConflict to resource.

Accept conflict 

---

CHANGELOG.md
src/Service/MicrosoftGraphBookingService.php
src/Service/MicrosoftGraphHelperService.php
tests/Api/BookingTest.php
tests/Service/MicrosoftGraphBookingServiceTest.php

https://jira.itkdev.dk/browse/BOOKING-247
Add acceptConflict tests.

Add acceptConflict tests.

---

CHANGELOG.md
config/packages/monolog.yaml

https://jira.itkdev.dk/browse/SUPP0RT-1149
Added null handler for deprecation warnings in production.

SUPPORT-1149: Added null handler for deprecation warnings in production

---

CHANGELOG.md
composer.json
composer.lock
src/DataProvider/UserBookingCollectionDataProvider.php
src/Service/MicrosoftGraphBookingService.php
tests/Service/MicrosoftGraphBookingServiceTest.php

https://jira.itkdev.dk/browse/SUPP0RT-1149
Changed how location email is found for event.
Set displayName from resource database when set.

SUPPORT-1149: Changed to another heuristic for finding location email

---

CHANGELOG.md
src/DataProvider/UserBookingCollectionDataProvider.php
src/Service/BookingServiceInterface.php
src/Service/MicrosoftGraphBookingService.php
tests/Service/MicrosoftGraphBookingServiceTest.php

https://jira.itkdev.dk/browse/SUPP0RT-1149
Changed user bookings to paginated

SUPPORT-1149: Changed user bookings to paginated

---

CHANGELOG.md
src/Service/MicrosoftGraphBookingService.php

https://jira.itkdev.dk/browse/SUPP0RT-1149
Only search in subject for user bookings.

SUPPORT-1149: Only search in subject

---

config/api_platform/user-booking-cache-entry.yaml
migrations/Version20230918105246.php
public/api-spec-v1.json
public/api-spec-v1.yaml
src/Entity/Main/UserBookingCacheEntry.php
src/Repository/Main/UserBookingCacheEntryRepository.php

https://jira.itkdev.dk/browse/BOOKING-273
- Add migration
- Add entity definition
- Add api spec definition

Added entity definition, migration and api spec

---

.docker/data/.gitignore
.env
CHANGELOG.md
config/packages/messenger.yaml
docker-compose.dev.yml
docker-compose.override.yml
docker-compose.redirect.yml
docker-compose.server.override.yml
docker-compose.server.yml
docker-compose.yml

https://jira.itkdev.dk/browse/BOOKING-272
- Remove Rabbit MQ to lower changes of failure. As the amount of messages in the system is relative low, this extra service really it not needed. 
- Updated docker setup to match the newest ITKDev version.
N/A
N/A

272: Removed Rabbit MQ from the mix

---

CHANGELOG.md
composer.json
composer.lock
src/Command/UserBookingUpdateCacheCommand.php
src/Controller/GetStatusByIdsController.php
src/Doctrine/UserBookingCacheEntryExtension.php
src/Service/BookingServiceInterface.php
src/Service/MicrosoftGraphBookingService.php
src/Service/UserBookingCacheService.php

https://jira.itkdev.dk/browse/BOOKING-292
Updated bundles.

BOOKING-292: Composer update

---

.github/workflows/pr.yml
CHANGELOG.md

* Updated GitHub workflow images

Updated GitHub workflow images

---

CHANGELOG.md
src/Controller/CreateBookingController.php
tests/AbstractBaseApiTestCase.php
tests/Controller/CancelBookingControllerTest.php
tests/Controller/CreateBookingControllerTest.php

https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/4050
Adds tests of create and cancel booking controllers.
N/A
If you have any further comments or questions for the reviewer please add them here.

Added Create and Cancel booking controller tests

---

.env
CHANGELOG.md
config/services.yaml
src/Repository/Resources/AAKResourceRepository.php
src/Service/ResourceService.php
tests/Service/ResourceServiceTest.php

https://leantime.itkdev.dk/#/tickets/showTicket/4327
Added resource exclude list

4327: Added resource exclude list
